# Generated by Django 5.0.7 on 2024-07-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
