# Generated by Django 5.0.7 on 2024-07-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
